default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nobe_test_development

test:
  <<: *default
  database: nobe_test_test

production:
  <<: *default
  database: nobe_test_production
  username: nobe_test
  password: <%= ENV['NOBE_TEST_DATABASE_PASSWORD'] %>
